sudo: required
language: go

go:
    - 1.9

install:
    - source .travis/install_gurobi.sh
    - ./install.sh

script:
    - go build -tags pre_xenial
    - go test -race -coverprofile=coverage.txt -covermode=atomic -v -tags="pre_xenial travis"

after_success:
    - bash <(curl -s https://codecov.io/bash)
